# Generated by Django 3.0.9 on 2020-08-07 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('population', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'main_cmpo',
            },
        ),
        migrations.CreateModel(
            name='Excellence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155)),
            ],
            options={
                'verbose_name': 'กลุ่มงาน',
                'verbose_name_plural': 'กลุ่มงาน',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Ssj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155)),
                ('hospcode', models.CharField(default='00068', max_length=5)),
            ],
            options={
                'verbose_name': 'จังหวัด',
                'verbose_name_plural': 'จังหวัด',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('ssj', models.CharField(choices=[('00068', 'ชุมพร'), ('00067', 'ระนอง'), ('00066', 'สุราษฎร์ธานี'), ('00062', 'นครศรีธรรมราช'), ('00063', 'กระบี่'), ('00064', 'พังงา'), ('00065', 'ภูเก็ต')], default='00068', max_length=100)),
                ('response', models.CharField(choices=[('1', 'พัฒนายุทธศาสตร์สาธารณสุข'), ('2', 'บริหารทั่วไป'), ('3', 'ทันตสาธารณสุข'), ('4', 'ควบคุมโรคติดต่อ'), ('5', 'คุ้มครองผู้บริโภคและเภสัชสาธารณสุข'), ('6', 'บริหารทรัพยากรบุคคล'), ('7', 'นิติกร'), ('8', 'พัฒนาคุณภาพและสรุปแบบบริการ'), ('9', 'ส่งเสริมสุขภาพ'), ('10', 'อนามัยสิ่งแวดล้อมและอาชีวอนามัย'), ('11', 'ประกันสุขภาพ'), ('12', 'ควบคุมโรคไม่ติดต่อ สุขภาพจิตและยาเสพติด'), ('13', 'แพทย์แผนไทยและการแพทย์ทางเลือก'), ('14', 'สุขศึกษาประชาสัมพันธ์'), ('15', 'None')], default='1', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_code', models.CharField(max_length=15, unique=True)),
                ('kpi_name', models.TextField(blank=True)),
                ('kpi_group', models.CharField(blank=True, max_length=15)),
                ('kpi_group_name', models.CharField(blank=True, max_length=55)),
                ('goal', models.CharField(blank=True, max_length=11)),
                ('goal_descript', models.TextField(blank=True)),
                ('cri_type', models.CharField(blank=True, max_length=15)),
                ('unit', models.CharField(blank=True, max_length=55)),
                ('formular', models.CharField(blank=True, max_length=55)),
                ('formular_type', models.CharField(blank=True, max_length=15)),
                ('descript_a', models.TextField(blank=True)),
                ('descript_b', models.TextField(blank=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Reponse')),
            ],
            options={
                'verbose_name': 'ตัวชี้วัด KPI',
                'verbose_name_plural': 'ตัวชี้วัด KPI',
                'ordering': ('kpi_code',),
            },
        ),
        migrations.CreateModel(
            name='KeyInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2020', '2563')], default='2020', max_length=6)),
                ('a1', models.CharField(blank=True, max_length=55)),
                ('b1', models.CharField(blank=True, max_length=55)),
                ('a2', models.CharField(blank=True, max_length=55)),
                ('b2', models.CharField(blank=True, max_length=55)),
                ('a3', models.CharField(blank=True, max_length=55)),
                ('b3', models.CharField(blank=True, max_length=55)),
                ('a4', models.CharField(blank=True, max_length=55)),
                ('b4', models.CharField(blank=True, max_length=55)),
                ('a5', models.CharField(blank=True, max_length=55)),
                ('b5', models.CharField(blank=True, max_length=55)),
                ('a6', models.CharField(blank=True, max_length=55)),
                ('b6', models.CharField(blank=True, max_length=55)),
                ('a7', models.CharField(blank=True, max_length=55)),
                ('b7', models.CharField(blank=True, max_length=55)),
                ('a8', models.CharField(blank=True, max_length=55)),
                ('b8', models.CharField(blank=True, max_length=55)),
                ('a9', models.CharField(blank=True, max_length=55)),
                ('b9', models.CharField(blank=True, max_length=55)),
                ('a10', models.CharField(blank=True, max_length=55)),
                ('b10', models.CharField(blank=True, max_length=55)),
                ('a11', models.CharField(blank=True, max_length=55)),
                ('b11', models.CharField(blank=True, max_length=55)),
                ('a12', models.CharField(blank=True, max_length=55)),
                ('b12', models.CharField(blank=True, max_length=55)),
                ('input_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('hospcode', models.ForeignKey(default='00068', on_delete=django.db.models.deletion.CASCADE, to='main.Ssj')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Kpi')),
                ('response', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main.Reponse')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
