# Generated by Django 3.0.9 on 2020-08-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={},
        ),
        migrations.AlterField(
            model_name='keyinput',
            name='kpi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Kpi'),
        ),
        migrations.AlterField(
            model_name='keyinput',
            name='response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Reponse'),
        ),
        migrations.AlterModelTable(
            name='keyinput',
            table='main_keyinput',
        ),
        migrations.AlterModelTable(
            name='kpi',
            table='main_kpi',
        ),
        migrations.AlterModelTable(
            name='reponse',
            table='main_response',
        ),
    ]
