# Generated by Django 3.1 on 2020-08-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chospital',
            fields=[
                ('hospcode', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hosname', models.CharField(blank=True, max_length=255, null=True)),
                ('hostype', models.CharField(blank=True, max_length=2, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('road', models.CharField(blank=True, max_length=50, null=True)),
                ('mu', models.CharField(blank=True, max_length=2, null=True)),
                ('subdistcode', models.CharField(blank=True, max_length=2, null=True)),
                ('distcode', models.CharField(blank=True, max_length=2, null=True)),
                ('provcode', models.CharField(blank=True, max_length=2, null=True)),
                ('postcode', models.CharField(blank=True, max_length=5, null=True)),
                ('hoscodenew', models.CharField(blank=True, max_length=9, null=True)),
                ('bed', models.IntegerField(blank=True, null=True)),
                ('level_service', models.CharField(blank=True, max_length=255, null=True)),
                ('bedhos', models.CharField(blank=True, max_length=5, null=True)),
                ('hdc_regist', models.IntegerField(blank=True, null=True)),
                ('dep', models.CharField(blank=True, max_length=5, null=True)),
                ('hmain_sent', models.CharField(blank=True, max_length=5, null=True)),
                ('regiter_date', models.DateField(blank=True, null=True)),
                ('mocode', models.CharField(max_length=5)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Excellence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
